# -*- coding: mbcs -*-
# Do not delete the following import lines
from abaqus import *
from abaqusConstants import *
import __main__

import section
import regionToolset
import displayGroupMdbToolset as dgm
import part
import material
import assembly
import step
import interaction
import load
import mesh
import optimization
import job
import sketch
import visualization
import xyPlot
import displayGroupOdbToolset as dgo
import connectorBehavior
import os



#-------------------------------------------------------------------------------------------
#入力事項
cpartname='tp'
ltp=1400.0;
#断面ファイル
sk0='tp00'
#フランジ面スケッチファイル
sk1='tp01'


#シェル厚の設定
ttp=25

#スケッチの単なる読み込み
from dxf2abq import importdxf
importdxf(fileName='lib/'+sk0+'.dxf')
importdxf(fileName='lib/'+sk1+'.dxf')
#-------------------------------------------------------------------------------------------
#パートモジュール
#スケッチ押し出し
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
sheetSize=200.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.sketchOptions.setValues(gridOrigin=(lctp*0.5, 0.0))
s.retrieveSketch(sketch=mdb.models['Model-1'].sketches[sk0])
session.viewports['Viewport: 1'].view.fitView()
p = mdb.models['Model-1'].Part(name=cpartname, dimensionality=THREE_D, 
type=DEFORMABLE_BODY)
p = mdb.models['Model-1'].parts[cpartname]
p.BaseShell(sketch=s)
s.unsetPrimaryObject()
p = mdb.models['Model-1'].parts[cpartname]
session.viewports['Viewport: 1'].setValues(displayedObject=p)
del mdb.models['Model-1'].sketches['__profile__']


#スケッチ
p = mdb.models['Model-1'].parts[cpartname]
f, e1, d2 = p.faces, p.edges, p.datums
t = p.MakeSketchTransform(sketchPlane=f[0], sketchUpEdge=e1[38], 
sketchPlaneSide=SIDE1, origin=(ltp*0.5, 0.0, 0.0))
s1 = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
sheetSize=2828.42, gridSpacing=70.71, transform=t)
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p = mdb.models['Model-1'].parts[cpartname]
p.projectReferencesOntoSketch(sketch=s1, filter=COPLANAR_EDGES)
s1.retrieveSketch(sketch=mdb.models['Model-1'].sketches[sk1])
s1.move(vector=(-ltp*0.5, 0.0), objectList=(g[42], g[43], g[44], g[45], g[46], 
g[47], g[48], g[49], g[50], g[51], g[52], g[53], g[54], g[55], g[56], 
g[57], g[58], g[59], g[60], g[61], g[62], g[63], g[64], g[65], g[66], 
g[67], g[68], g[69], g[70], g[71], g[72], g[73], g[74], g[75], g[76], 
g[77], g[78], g[79], g[80], g[81], g[82]))
p = mdb.models['Model-1'].parts[cpartname]
f = p.faces
pickedFaces = f.getSequenceFromMask(mask=('[#1 ]', ), )
e, d1 = p.edges, p.datums
p.PartitionFaceBySketch(sketchUpEdge=e[38], faces=pickedFaces, sketch=s1)
s1.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__profile__']



#------------------------------------------------------------------------
#シェル厚。これはシェルcfの12mm厚
mdb.models['Model-1'].HomogeneousShellSection(name='tp', preIntegrate=OFF, 
material=mat, thicknessType=UNIFORM, thickness=ttp, 
thicknessField='', idealization=NO_IDEALIZATION, 
poissonDefinition=DEFAULT, thicknessModulus=None, temperature=GRADIENT, 
useDensity=OFF, integrationRule=SIMPSON, numIntPts=5)


#シェル厚の割り当て
p = mdb.models['Model-1'].parts[cpartname]
f = p.faces
faces = f.getSequenceFromMask(mask=('[#ffffffff #3fff ]', ), )
region = regionToolset.Region(faces=faces)
p = mdb.models['Model-1'].parts[cpartname]
p.SectionAssignment(region=region, sectionName='tp', offset=0.0, 
offsetType=MIDDLE_SURFACE, offsetField='', 
thicknessAssignment=FROM_SECTION)


#------------------------------------------------------------------------
#メッシュの割り当て
p = mdb.models['Model-1'].parts[cpartname]
f = p.faces
pickedRegions = f.getSequenceFromMask(mask=('[#ffffffff #3fff ]', ), )
p.setMeshControls(regions=pickedRegions, elemShape=TRI, allowMapped=False)
p = mdb.models['Model-1'].parts[cpartname]
f = p.faces
pickedRegions = f.getSequenceFromMask(mask=('[#0 #14c0 ]', ), )
p.setMeshControls(regions=pickedRegions, elemShape=QUAD, technique=STRUCTURED)


#メッシュシードの割り当て
p = mdb.models['Model-1'].parts[cpartname]
p.seedPart(size=30.0, deviationFactor=0.1, minSizeFactor=0.1)


#局所メッシュシードの割り当て
p = mdb.models['Model-1'].parts[cpartname]
e = p.edges
pickedEdges = e.getSequenceFromMask(mask=('[#ffffffff:2 #ff ]', ), )
p.seedEdgeByNumber(edges=pickedEdges, number=8, constraint=FINER)

#メッシュの実行
p = mdb.models['Model-1'].parts[cpartname]
p.generateMesh()



#サーフェスの設定
p = mdb.models['Model-1'].parts['tp']
s = p.faces
side12Faces = s.getSequenceFromMask(mask=('[#381f81c0 ]', ), )
p.Surface(side12Faces=side12Faces, name='s0')

p = mdb.models['Model-1'].parts['tp']
s = p.faces
side12Faces = s.getSequenceFromMask(mask=('[#c0e07038 #1 ]', ), )
p.Surface(side12Faces=side12Faces, name='s1')

p = mdb.models['Model-1'].parts['tp']
s = p.faces
side12Faces = s.getSequenceFromMask(mask=('[#7000e07 #e ]', ), )
p.Surface(side12Faces=side12Faces, name='s2')



